import java.lang.Exception

fun main() {
    var number:Int? = null
    try {

    }catch (e:Exception){

    }
}